### ISSUE TITLE
AMRBART model does not available in Hugging Face hub

### ISSUE THREAD

**Issue by elifssamplespace** [muyeby/AMRBART#10]
Thank you for sharing this exellent work. I would like to ask you if you could re-upload AMRBART-large and base models. Because I keep getting this error 

OSError: Can't load config for 'xfbai/AMRBART-base'. Make sure that:

- 'xfbai/AMRBART-base' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'xfbai/AMRBART-base' is the correct path to a directory containing a config.json file

 Thank you for your help!

**Comment by goodbai-nlp** [comment]
Hi, I am able to load the config and models normally. Could you check whether your device has access to the Internet?
![image](https://user-images.githubusercontent.com/9586457/181934002-9e108672-0717-4295-a7e3-1d87e6439cc8.png)

**Comment by elifssamplespace** [comment]
Thank you for reply,
I don't know if the problem was with my internet connection but it is working now. Thank for you time :)
