### ISSUE TITLE
Inference Needs train, test and val datasets to run

### ISSUE THREAD

**Issue by SreehariSankar** [muyeby/AMRBART#12]
To run inference (say AMR-->Text) train, test and validation sets are required.
Please provide a way to run the model on a pre-processed text file without needing all this data.

**Comment by goodbai-nlp** [comment]
Hi, we will update the code later. As an interim solution, you can take the files in the example directory as train/validation data.

**Comment by SreehariSankar** [comment]
Thanks!
Just one last question: Could you please let me know how to tokenize a pre-processed AMR graph so that I can directly input it to the BART model? You can assume I have all the things (BART model ready, Tokenizer ready, etc). Should i just take the amr graph as a string and pass it to the tokenizer and then pass it to BART?
Thanks! Much appreciated.

**Comment by goodbai-nlp** [comment]
Hi, we implement an [AMRBartTokenizer](https://github.com/goodbai-nlp/AMRBART/blob/main/fine-tune/model_interface/tokenization_bart.py) to tokenize pre-processed AMRs. To use the tokenizer, you can do the following steps:
1. create a tokenizer instance:
```
tokenizer = AMRBartTokenizer.from_pretrained(
        "facebook/bart-large",
    )
```
2. tokenize the pre-processed AMR strings and transform into ids:
```
amr_ids = [tokenizer.amr_bos_token_id] + tokenizer.tokenize_amr(amr_string.split())[:max_src_length - 2] + [tokenizer.amr_eos_token_id]
```
If you use AMRBART, please follow [here](https://github.com/goodbai-nlp/AMRBART/blob/ffe79bdbe99cb51ef8313b4b206a862bd3f6f1d2/fine-tune/data_interface/dataset.py#L197) to add special tokens.

**Comment by SreehariSankar** [comment]
Thanks! All the best with your ACL 2022!

**Comment by goodbai-nlp** [comment]
This bug has been fixed.
