### ISSUE TITLE
Question about generating text

### ISSUE THREAD

**Issue by tingchihc** [muyeby/AMRBART#19]
In the AMRBART, could we use this to generate multiple sentences?

**Comment by goodbai-nlp** [comment]
Hi, @ting-chih

You may try to assign [`num_return_sequences`](https://huggingface.co/docs/transformers/v4.28.1/en/main_classes/text_generation#transformers.GenerationConfig.num_return_sequences(int,)) with `n` to generate `n` outputs for a given input.
