### ISSUE TITLE
HTTP Error while running evaluation script

### ISSUE THREAD

**Issue by ruchika2ar** [muyeby/AMRBART#2]
Hi,
I am facing the below error when running the command: [](https://github.com/muyeby/AMRBART#amr-to-text-generation)bash finetune_AMRbart_amrparsing.sh /path/to/pre-trained/AMRBART/ gpu_id
I am unable to find the cause and would really appreciate any help! Thanks a lot!
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/33141946/160681934-9eeebe87-b07b-4e7e-acdd-fba09f96f4af.png">

**Comment by goodbai-nlp** [comment]
Hi, 

Please refer to [this issue](https://github.com/muyeby/AMRBART/issues/1).
