### ISSUE TITLE
Curious about AMR to text (node to text token alignment)

### ISSUE THREAD

**Issue by xu1998hz** [muyeby/AMRBART#5]
Hi @muyeby @cylnlp , thanks for your patient answer previously.
This is a great work and I am new to this task. I am curious that is there any heuristic way to align your AMR graph nodes back to text tokens?

**Comment by cylnlp** [comment]
You may refer to [JAMR](https://aclanthology.org/P14-1134/).

**Comment by xu1998hz** [comment]
Thanks
