### ISSUE TITLE
PenmanBART Tokenizer

### ISSUE THREAD

**Issue by tdt98** [muyeby/AMRBART#7]
Thank you for sharing your great work. I would like to ask if you could upload the weights of your trained PENMANBartTokenizer. Thank you for your help!

**Comment by tdt98** [comment]
Sorry for bothering, I would like to ask if you could upload the model checkpoint for AMR parsing using BART base, I only see your model using BART large? Thank you for your help!

**Comment by goodbai-nlp** [comment]
Uploaded.
