### ISSUE TITLE
Different decoding methods

### ISSUE THREAD

**Issue by hoangftran** [muyeby/AMRBART#8]
Hi sir, thank you for your great work!

Have you run experiments with different decoding methods? I see in the code you use beam search for decoding, why do you choose beam search, and have you try with top-k sampling? Thank you.

**Comment by goodbai-nlp** [comment]
Hi,

We choose beam search instead of other methods for decoding because we need to ensure comparability with previous seq2seq approaches. It might be interesting to try methods beyond beam search. If you have any findings, welcome to post the results here.
